import React from 'react';
import './TermsService.css'
import { motion } from 'framer-motion';
import { variants } from '../../animation-variants.js';
import { transitions } from '../../page-transitions.js';
import Img2 from '../images/white-list-icon-gradient.svg';

function TermsService() {

    return (
        <>
            <motion.body 
                className="terms-service-page"
                initial="slideOutY" 
                animate="slideInY" 
                exit="slideOutY"
                variants={variants}
                transition={transitions.tweenEaseOutSlow}    
            >
                {window.scroll(0,0)}
               
                <div className="terms-service-container">
                <img className = "terms-service-bg" src = {Img2} alt="WhiteList"></img>
                    <h1 className="terms-service-h1">Terms of Service</h1>
                    <p className="terms-service-p">Welcome to WhiteList. We provide a platform for partner properties to list their spaces and reach a wider scope of potential tenants. With WhiteList, tenants can find accommodation through the platform’s geo-location, filtering of price, area, and other details. By accessing the WhiteList.com website, (the "Website") you agree to be bound by these Terms of Use (this "Agreement"), whether or not you register as a member of WhiteList. If you wish to become a member and make use of WhiteList's Services (the "Services"), please read these Terms of Use. The term "Website" is deemed to refer to the use of the Services by means of a computer, a mobile device or a mobile application.
                    You should also read the WhiteList Privacy Policy, which is incorporated by reference into this Agreement and available on the Website. If you do not accept and agree to be bound by all of the terms of this Agreement, including the Whitelist Privacy Policy, do not use the Website or the Services. Please contact us with any questions regarding this Agreement.</p>
                    
                    <h2 className="terms-service-h2">1. Acceptance of Terms of Use Agreement</h2>
                    <p className="terms-service-p2">1.1 This Agreement is an electronic contract that establishes the legally binding terms you must accept to use the Website and to become a "Member." For purposes of this Agreement, the term "Member" means a person who provides information to WhiteList on the Website or to participate in the Services in any manner, whether such person uses the Services as a free member or a subscriber. You acknowledge and agree that Members of WhiteList may be part of an online community that includes other websites owned by WhiteList or its affiliates. This Agreement includes WhiteList's Privacy Policy published on the Website and terms disclosed and agreed to by you if you become a member or advertiser or if you purchase Services or accept additional features, products, or Services we offer on the Website, such as specific terms and terms governing features, billing, free trials, discounts and promotions.
                    <br /><br />1.2 By accessing the Website or using the Services, you accept this Agreement and agree to the terms, conditions, and notices contained or referenced herein, and consent to have this Agreement and all paid notices provided to you in electronic form. Please print a copy of this Agreement for your records. This Agreement may be modified by WhiteList from time to time, and such modifications are effective upon posting by WhiteList on the Website.
                    <br /><br />1.3 By using the Services, you consent to receive this Agreement in electronic form by using the Services. To withdraw this consent, you must cease using the Services and terminate your account.</p>
                    <h2 className="terms-service-h2">Our Services</h2>
                    <p className="terms-service-p2">1.4 Our service is a platform that connects the Property to tenants who are looking for accommodations which are listed in WhiteList.ph.
                    <br/> <br />Properties are considered independent third party service providers under agreement with WhiteList. Unless otherwise agreed by WhiteList.ph in a separate written agreement with you, the Services are made available solely for your personal, noncommercial use.
                    <br /><br />YOU ACKNOWLEDGE THAT WhiteList.ph DOES NOT PROVIDE ACCOMMODATION OR LOGISTICS SERVICES OR FUNCTION AS A PROPERTY.</p>
                    <h2 className="terms-service-h2">2. Eligibility</h2>
                    <p className="terms-service-p2">2.1 You must be at least 18 years of age to access and use the Services. Any use of the Services is void where prohibited. By accessing and using the Website, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement. Using the Services may be prohibited or restricted in certain countries. If you use the Services from outside of the United States, you are responsible for complying with the laws and regulations of the territory from which you access or use the Website or the Services.</p>
                    <h2 className="terms-service-h2">3. Membership</h2>
                    <p className="terms-service-p2">3.1 You may register as a Member at no cost. As a Member, you may use some, but not all, of the features and Services that may be available within the Services. To access or use certain additional features and Services which WhiteList may in its sole discretion offer at certain times, you may also become a paying subscriber to the Services. The policies of such additional Services that are disclosed to you when you subscribe to the Services are a part of this Agreement. Absent special offers, you acknowledge and agree that if you are not a subscriber, you will not be able to use all the features and Services available within the Services. A Member profile (both subscribers and non-subscribers) may remain posted on the Website even if that Member is not actively using the Services.</p>
                    <h2 className="terms-service-h2">4. Term and Termination</h2>   
                    <p className="terms-service-p2">4.1 This Agreement will remain in full force and in effect while you use the Services and/or are a Member.
                    <br /> <br /> 4.2 All listings are active until the termination date ("Listing Termination Date") set by the Member posting the listing. If such a Listing Termination Date is not set, then the listing is considered active.
                    <br /> <br />4.3 You may deactivate your Listing at any time by setting the Listing Termination Date.
                    <br /> <br />4.4 You may change or cancel your membership at any time, for any reason, by sending a notice of cancellation email to: hello@WhiteList.ph.
                    <br /> <br />4.5 WhiteList may terminate or suspend your listing and/or membership in the Services at any time without notice if WhiteList believes that you have breached this Agreement. Upon such termination or suspension, you will not be entitled to any refund of unused fees (if applicable) and, if applicable, all unpaid amounts and other fees you owe will immediately be due. WhiteList is not required to disclose, and may be prohibited by law from disclosing, the reason for the termination or suspension of your account.
                    <br /> <br />4.6 After your membership or listing is terminated for any reason, all terms of this Agreement survive such termination, and continue in full force and effect, except for any terms that by their nature expire or are fully satisfied.
                    <br /> <br />4.7 In the event of any breakdown or stoppage of our website, we will issue credit upon request or on a case to case basis. Credit provided will only be in the form of extending the listing or paid subscription which is equivalent to the days the website was down.
                    <br /> <br />4.8 WhiteList has the right to decline any membership.</p> 

                    <h2 className="terms-service-h2">5. Your Interactions with Other Members</h2>
                    <p className="terms-service-p2">5.1 YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER MEMBERS. YOU UNDERSTAND THAT WhiteList CURRENTLY DOES NOT CONDUCT CRIMINAL BACKGROUND CHECKS OR SCREENINGS ON ITS MEMBERS. WhiteList ALSO DOES NOT INQUIRE INTO THE BACKGROUNDS OF ALL OF ITS MEMBERS OR ATTEMPT TO VERIFY THE STATEMENTS OF OR INFORMATION PROVIDED BY ITS MEMBERS. WhiteList MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF MEMBERS OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE MEMBERS. WhiteList RESERVES THE RIGHT TO CONDUCT ANY CRIMINAL BACKGROUND CHECK OR OTHER SCREENINGS (SUCH AS SEX OFFENDER REGISTER SEARCHES), AT ANY TIME AND USING AVAILABLE PUBLIC RECORDS.
                    <br /><br /> 5.2 WhiteList is not responsible for the conduct of any Member. As noted in and without limiting Sections 24 and 25 below, in no event shall WhiteList, its affiliates, or its partners be directly or indirectly liable for any losses or damages whatsoever, whether direct, indirect, general, special, compensatory, consequential, and/or incidental, arising out of or relating to the conduct of you or anyone else in connection with the use of the Website or Services including, without limitation, death, bodily injury, emotional distress, and/or any other damages resulting from communications or meetings with other Members or persons you meet through the Services. You agree to take all necessary precautions in all interactions with other Members, particularly if you decide to communicate off the Website or meet in person, or if you decide to send money to another Member. You understand that WhiteList makes no guarantees, either express or implied, regarding your ultimate compatibility with individuals you meet through the Services. You should not provide your financial information (for example, your credit card or bank account information), or wire or otherwise send money, to other Members except by going through WhiteList.</p>
                    
                    <h2 className="terms-service-h2">6. Proprietary Rights.</h2>
                    <p className="terms-service-p2">6.1 WhiteList owns and retains all proprietary rights in the Website and the Services, and in all content, trademarks, trade names, Services marks and other intellectual property rights related thereto. The Website contains the copyrighted material, trademarks, and other proprietary information of WhiteList and its licensors. You agree to not copy, modify, transmit, create any derivative works from, make use of, or reproduce in any way any copyrighted material, trademarks, trade names, Services marks, or other intellectual property or proprietary information accessible on the Website or through the Services, without first obtaining the prior written consent of WhiteList or, if such property is not owned by WhiteList, the owner of such intellectual property or proprietary rights. You agree to not remove, obscure or otherwise alter any proprietary notices appearing on any content, including copyright, trademark and other intellectual property notices.</p>
                    
                    <h2 className="terms-service-h2">7. Content Posted by You on the Website.</h2>
                    <p className="terms-service-p2">7.1 You are required to maintain the confidentiality of all logins and passwords. You are solely responsible for the activities that occur under your account, login or password.
                    <br /><br />
                    7.2 You are solely responsible for the content and information that you post, upload, publish, link to, transmit, record, display or otherwise make available (hereinafter, "post") on the Services or transmit to other Members, including emails, videos such as but not limited to streaming videos, photographs, voice notes, recordings or profile text, whether publicly posted or privately transmitted (collectively, "Content"). You may not post on the Website or as part of the Services, or transmit to WhiteList or any other Member either via the Website or outside of it, any offensive, inaccurate, abusive, obscene, profane, sexually oriented, threatening, intimidating, harassing, racially offensive, or illegal material, or any material that infringes or violates another person's rights, including intellectual property rights, and rights of privacy and publicity. You represent and warrant that all information that you submit upon registration is accurate and truthful and that you will promptly update any information provided by you that subsequently becomes inaccurate, misleading or false.
                    <br /><br />
                    7.3 You understand and agree that WhiteList may, but is not obligated to, monitor or review any Content you post on the Website or as part of a Services. WhiteList may delete any Content, in whole or in part, that in the sole judgment of WhiteList violates this Agreement or may harm the reputation of the Website or WhiteList. WhiteList may restrict the number of emails which a Member may send to other Members in any 24-hour period to a number which we deem appropriate in our sole discretion.
                    <br /><br />
                    7.4 By posting Content on the Website or as part of the Services, you automatically grant to WhiteList, its affiliates, licensees, and successors, an irrevocable, perpetual, non-exclusive, fully paid-up, worldwide right and license to (i) use, copy, store, perform, display, reproduce, record, play, adapt, modify, and distribute the Content, (ii) prepare derivative works of the Content or incorporate the Content into other works, (iii) sell all contents without sharing proceeds generated with you there from. You represent and warrant that any posting and use of your Content by WhiteList will not infringe or violate the rights of any third party and/or you.
                    <br /><br />
                    7.5 In addition to the types of Content described in Section 7.2 above, the following is a partial list of the kind of Content that is prohibited on the Website. You may not post, upload, display or otherwise make available Content that:
                    <br /><br />
                    7.5.1 promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;
                    <br /><br />
                    7.5.2 advocates harassment or intimidation of another person;
                    <br /><br />
                    7.5.3 requests money from, or is intended to otherwise defraud other users of the Website or Services;
                    <br /><br />
                    7.5.4 involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming" (or "spimming", "phishing", "trolling" or similar activities);
                    <br /><br />
                    7.5.5 promotes information that is false or misleading, or promotes illegal activities or conduct that is defamatory, libelous or otherwise objectionable;
                    <br /><br />
                    7.5.6 promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated images, audio or video, or links to pirated images, audio or video files;
                    <br /><br />
                    7.5.7 contains video, audio photographs, or images of another person without his or her permission, or in the case of a minor, the minor's legal guardian;
                    <br /><br />
                    7.5.8 contains restricted or password only access pages, or hidden pages or images that are not linked to or from another accessible page;
                    <br /><br />
                    7.5.9 provides material that exploits people in a sexual, violent or other illegal manner, or solicits personal information from anyone under the age of 18;
                    <br /><br />
                    7.5.10 provides instructional information about illegal activities such as but not limited to making or buying illegal weapons or drugs, violating someone's privacy, or providing, disseminating or creating computer viruses;
                    <br /><br />
                    7.5.11 contains viruses, time bombs, trojan horses, cancelbots, worms or other harmful or disruptive codes, components or devices;
                    <br /><br />
                    7.5.12 impersonates or otherwise misrepresents affiliation, connection or association with any person or entity;
                    <br /><br />
                    7.5.13 provides information or data you do not have a right to make available under law or under contractual or fiduciary relationships such as inside information, proprietary, and confidential information;
                    <br /><br />
                    7.5.14 disrupts the normal flow of dialogue, causes a screen to "scroll" faster than other users are able to type, or otherwise negatively affects other users' ability to engage in real time exchanges;
                    <br /><br />
                    7.5.15 solicits passwords or personal identifying information for commercial or unlawful purposes from other users or disseminates another person's personal information without his or her permission; and
                    <br /><br />
                    7.5.16 publicizes or promotes commercial activities and/or sales without WhiteList’s prior written consent such as contests, sweepstakes, barter, advertising, and pyramid schemes.
                    <br /><br />
                    7.6 WhiteList reserves the right in its sole discretion, to investigate and take appropriate legal action against anyone who violates this provision, including removing the offending communication from the Website or Services and terminating or suspending the membership of such violators. Your use of the Website and Services, including all Content you post through the Services, must comply with all applicable laws and regulations. You agree that WhiteList may access, preserve and disclose your account information and Content if required to do so by law or in a good faith belief that such access, preservation or disclosure is reasonably necessary, such as to: (i) comply with legal process; (ii) enforce this Agreement; (iii) respond to claims that any Content violates the rights of third parties; (iv) respond to your requests for customer Services or allow you to use the Website in the future; or (v) protect the rights, property or personal safety of WhiteList or any other person.</p>
                    
                    <h2 className="terms-service-h2">8. Prohibited Activities</h2>
                    <p className="terms-service-p2">WhiteList reserves the right to investigate and/or terminate your membership if you have misused the Services or behaved in a way WhiteList regards as inappropriate or unlawful, including actions or communications the occur off the Website but involve Members you meet through the Services. The following is a partial list of the type of actions that you may not engage in with respect to the Services. You will not:
                    <br /><br />
                    8.1 impersonate any person or entity.
                    <br /><br />
                    8.2 solicit money from any Members.
                    <br /><br />
                    8.3 post any Content that is prohibited by Section 7.
                    <br /><br />
                    8.4 "stalk" or otherwise harass any person.
                    <br /><br />
                    8.5 express or imply that any statements you make are endorsed by WhiteList without our specific prior written consent.
                    <br /><br />
                    8.6 ask or use Members to conceal the identity, source, or destination of any illegally gained money or products.
                    <br /><br />
                    8.7 use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, "data mine", or in any way reproduce or circumvent the navigational structure or presentation of the Website, Services, or its contents.
                    <br /><br />
                    8.8 collect usernames and/or email addresses of members by electronic or other means for the purpose of sending unsolicited email or unauthorized framing of or linking to the Website.
                    <br /><br />
                    8.9 interfere with or disrupt the Services or the Website or the servers or networks connected to the Services or the Website.
                    <br /><br />
                    8.10 email or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment.
                    <br /><br />
                    8.11 forge headers or otherwise manipulate identifiers either directly or indirectly through use of third party software in order to disguise the origin of any information transmitted to or through the Website or Services.
                    <br /><br />
                    8.12 "frame" or "mirror" any part of the Services or the Website, without WhiteList's prior written authorization.
                    <br /><br />
                    8.13 use meta tags or code or other devices containing any reference to WhiteList, the Website or the Services, or any trademark, trade name, Services mark, logo or slogan of WhiteList, to direct any person to any other website for any purpose.
                    <br /><br />
                    8.14 modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Services or the Website or any software used on or for the Services or the Website, or cause others to do so.
                    <br /><br />
                    8.15 post, use, transmit or distribute, directly or indirectly, (e.g. screen scrape) in any manner or media any content or information obtained from the Website or the Services other than solely in connection with your use of the Services in accordance with this Agreement.</p>

                    <h2 className="terms-service-h2">9. Customer Services</h2>
                    <p className="terms-service-p2">9.1 WhiteList provides assistance and guidance through its customer care representatives. When communicating with our customer care representatives whether over the telephone, or via email or letter, you agree to not be abusive, obscene, profane, offensive, sexist, threatening, harassing, racially offensive, or to not otherwise behave inappropriately. Telephone calls between you and our customer care representatives may be recorded for quality assurance purposes. If we feel that your behavior towards any of our customer care representatives or other employees is at any time threatening or offensive, we reserve the right to immediately terminate your membership and you will not be entitled to any refund of unused advertisement fees.</p>
                    
                    <h2 className="terms-service-h2">10. Charges on Your Billing Account.</h2>
                    <p className="terms-service-p2">10.1 WhiteList bills you through an online account (your "Billing Account") for use of the Services. You agree to pay WhiteList or the property all charges at the prices you agreed to for any use of the Services by you or other persons, including your agents, using your Billing Account, and you authorize WhiteList to charge your chosen payment provider (your "Payment Method") for the Services. You agree to make payment using that selected Payment Method. WhiteList may correct any billing errors or mistakes that it makes even if it has already requested or received payment. This Section includes any agreements you made with WhiteList on the Website when becoming a Member or advertising at our Website. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution or other provider of your chosen Payment Method. If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, WhiteList may in its discretion terminate your account immediately. If WhiteList successfully disputes the reversal, and the reversed funds are returned, you are not entitled to a refund or to have your account or advertisement reinstated.</p>

                    <h2 className="terms-service-h2">11. Actions, Responsibilities, and Payments regarding Properties and Tenants</h2>
                    <p className="terms-service-p2">11.1 Definitions of Certain Key Terms
                    <br /><br />
                    Listing / Accommodation refers to a residential or other property listed by a Member as available for another Member to request a booking to rent through the Website and Services.
                    <br /><br />
                    Property refers to a Member who creates a Listing via the Website and Services.
                    <br /><br />
                    Tenant refers to a Member who requests from a Property a booking of an Accommodation via the Website or Services, or a Member who stays at an Accommodation, but is not the Property for such Accommodation.
                    <br /><br />
                    Booking Request Period refers to the time period beginning at the time when a Tenant requests a booking. As explained on the Website or Services, a Property may decide whether to confirm or decline that booking request within the Booking Request Period. Please note that different Booking Request Periods may apply in different instances.
                    <br /><br />
                    Tax or Taxes refers to any sales taxes, value added taxes ("VAT"), goods and services taxes, transient occupancy taxes, tourist or other visitor taxes, accommodation or accommodation taxes, or certain fees (e.g. convention center fees) that Accommodation providers may be required by law to collect and remit to governmental agencies, and other similar federal, state, municipal, national indirect or other withholding taxes, and personal or corporate income taxes.
                    <br /><br />
                    Accommodation Fees refers to the amounts payable by the Tenant for that Tenant's stay in the Accommodation. The Property, not WhiteList, is solely responsible for the Accommodation Fees of the Property's Listing. The Property in the Property's sole discretion may decide to include in these amounts (a) cleaning fee or any other fee permitted on the WhiteList platform, or (b) taxes which the Property has to collect, as determined by the Property.
                    <br /><br />
                    Reservation Fee refers to the amount payable by the Tenant for securing a reservation for their desired listing.
                    <br /><br />
                    Services Fees refers to the amount which is the sum of the Tenant Fees to the Property Fees.
                    <br /><br />
                    Total Fees refers to the amount which is the sum of the Accommodation Fees, the Tenant Fees, and any applicable Taxes
                    <br /><br />
                    11.2 Responsibilities of Properties and Tenants, and WhiteList's role as the Property's Limited Payment Transmitting Agent
                    <br /><br />
                    11.2.1 WhiteList is a housing listing portal designed to connect Properties and Tenants so they can potentially arrange bookings of Accommodations directly with each other. WhiteList is not an owner or operator of properties including but not limited to hotel rooms, motel rooms, other accommodations or Accommodations. WhiteList is not a provider of properties including but not limited to hotel rooms, motel rooms, other accommodations or Accommodations. WhiteList does not own, sell, resell, furnish, provide, rent, re-lease, manage and/or control properties including but not limited to hotel rooms, motel rooms, other accommodations or Accommodations or transportation or travel Services. Unless explicitly specified otherwise in the WhiteList platform, WhiteList's responsibilities are strictly limited to: (i) making available the Website and Services and (ii) serving as the limited payment transmitting agent of the Property to transmit payments from Tenants to the Property.
                    <br /><br />
                    11.2.2 Each Property hereby appoints WhiteList as the limited payment transmitting agent of the Property to transmit payments from Tenants to the Property. Each Property agrees that payment made by a Tenant via WhiteList shall be considered the same as payment made directly to the Property, and the Property will make the Accommodation available to the Tenant in the agreed-upon manner as if the Property has received the Accommodation Fees. Each Property agrees that WhiteList may, in accordance with the cancellation policy selected by the Property and reflected in the relevant Listing, (a) permit the Tenant to cancel the booking, and (b) refund via WhiteList to the Tenant the portion of the Accommodation Fees specified in the applicable cancellation policy. Each Property understands that WhiteList accepts payments from Tenants as the Property's limited payment transmitting agent, and that WhiteList's obligation to pay the Property is subject to and conditional on the successful receipt of the related payments from Tenants. WhiteList does not guarantee payments to Properties for amounts that have not been successfully received by WhiteList from Tenants. WhiteList assumes no liability for any acts or omissions of the Property in accepting appointment as the Property's limited payment transmitting agent.
                    <br /><br />
                    11.2.3 You agree that you are solely responsible for any and all information regarding the Listings and Content posted by you. You represent and warrant that any Listing you post and the booking of, or a Tenant's stay at, an Accommodation in a Listing you post (a) will (i) be compliant with all applicable laws including but not limited to zoning laws and laws governing residential, commercial or other rentals, Tax requirements, and rules and regulations that may be applicable to any Accommodation included in a Listing posted by you (including but not limited to all required permits, licenses and registrations), and (ii) not conflict with the rights of any third party, and (b) will not breach any agreements you have entered into with any third parties including but not limited to homeowners association, condominium, lease or rental agreements. At any time and without prior notice, WhiteList reserves the right to remove or disable access to any Listing for any reason, including Listings that WhiteList considers in its sole discretion to be objectionable for any reason, or in violation of these Terms or WhiteList's then prevailing Policies and Community Guidelines (provide link), or otherwise harmful to the Website or Services.
                    <br /><br />
                    11.2.4 You as a Property agree that WhiteList does not act as your contracting agent or as an insurer. If a Tenant requests a booking of your Accommodation or stays at your Accommodation, any agreement you enter into with such Tenant is an agreement solely between you and the Tenant to which WhiteList is not a party. WhiteList only serves as the limited payment transmitting agent of the Property to transmit payments from Tenants to the Property.
                    <br /><br />
                    11.2.5 Even though WhiteList provides certain tools to you as a Property to make informed decisions about other Members, you agree that you as a Property are solely responsible for your own acts, and omissions and are also solely responsible for the acts and omissions of any individuals who reside at or are otherwise present at the Accommodation at your request or invitation, excluding the Tenant and the individuals, if any, invited to the Accommodation by the Tenant.
                    <br /><br />
                    11.2.6 PROPERTIES SHOULD HAVE OR CHECK THEIR OWN INSURANCE: WhiteList recommends that the Properties obtain necessary or suitable insurance for their Accommodations. You as a Property should review carefully any insurance policy you may have for your Accommodation, paying particular attention to any exclusions to, and any deductibles that may be applicable for, such insurance policy, including but not limited to whether or not your insurance policy will cover the actions or inactions of Tenants and the individuals, if any, invited by the Tenants to the Accommodation.
                    <br /><br />
                    11.2.7 The Properties, not WhiteList, are solely responsible for honoring any confirmed bookings and making available any Accommodations reserved via the Website and Services. If you as a Tenant choose to enter into a transaction with a Property for booking an Accommodation, you agree that you will be required to enter into an agreement with the Property and to accept any terms, conditions, rules and restrictions associated with such Accommodation imposed by the Property. You agree that you, not WhiteList, will be (a) solely responsible for performing the obligations of such agreement, and (b) WhiteList is not a party to such agreement, and (c) with the exception of its payment obligations hereunder, WhiteList disclaims all liability regarding any such agreement. You also agree to, notwithstanding the fact that WhiteList is not a party to the agreement between you and the Property, WhiteList as the Property's limited payment transmitting agent for the sole purpose of transmitting the payment from you to the Property.
                    <br /><br />
                    11.2.8 WhiteList charges the Services Fees as consideration for providing the use of WhiteList's online platform and services. Where applicable, taxes may also be charged in respect of Property Fees and Tenant Fees. WhiteList deducts the Property Fees from the Accommodation Fees before remitting the balance to the Properties as described in these Terms. WhiteList will remit the balance to Properties via cash, check, direct deposit or other payment methods as described on the Website, in the Property's currency of choice, depending on the selections the Property makes via the Website and Services. Please note that WhiteList may impose or deduct foreign currency processing costs on or from any payments or payouts by WhiteList in currencies other than Philippine Peso. More information on any such costs or deductions will be available via the Website. Services Fees are non-refundable except as otherwise provided herein.
                    <br /><br />
                    11.2.9 Please note that WhiteList currently does not charge fees for the creation of Listings. However, as a Property you agree that WhiteList reserves the right in its sole discretion to charge you for and collect fees from you for the creation of Listings. Please note that WhiteList will provide notice of any Listing Fee collection via the Website and Services prior to the implementation of such procedure of charging a Listing fee.
                    <br /><br />
                    11.3 Registering as a Member
                    <br /><br />
                    11.3.1 Only Members can use the Website and Application to create a Listing or to book an Accommodation. To become a Member, you must first register to create an account ("WhiteList Account").
                    <br /><br />
                    11.3.2 You may register directly via the Website or indirectly using your account with certain third-party social networking Websites ("SNS Account"). To register indirectly, you need to link your WhiteList Account to your SNS Account by providing your SNS Account login information to WhiteList via the Website or Services, or by allowing WhiteList to access your SNS Account as permitted under the SNS's terms and conditions. You represent that you are entitled to disclose your SNS Account login information to WhiteList and/or grant WhiteList access to your SNS Account, for purposes including, but not limited to purposes described herein, without breach by you of any of the SNS's terms and conditions of the SNS and without obligating WhiteList to pay any fees or making WhiteList subject to any usage limitations imposed by such SNS Services providers. By granting WhiteList access to any SNS Accounts, you understand that WhiteList will access, make available and store (if applicable) any Content you have provided to your SNS Account ("SNS Content") and that such SNS Content is available on and through the Website and Services via your WhiteList Account. Unless otherwise specified in these Terms, all SNS Content, if any, will be deemed as Content posted by you on the Website and Services for all purposes of this Agreement. Depending on your selected SNS Account and subject to your privacy settings in such SNS Account, personally identifiable information that you post to such SNS Account will be available on and through your WhiteList Account on the Website and Services. Please note that if an SNS Account is terminated by the SNS Services provider, the SNS Content will no longer be available on and through the Website and Services. You are able to sever the connection between your WhiteList Account and your SNS Accounts at any time by using the "Settings" section of the Website, PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE SNS SERVICES PROVIDERS ASSOCIATED WITH YOUR SNS ACCOUNTS IS SOLELY GOVERNED BY YOUR AGREEMENT(S) WITH SUCH SNS SERVICES PROVIDERS. WhiteList makes no effort to review any SNS Content for any purpose, including but not limited to for accuracy, legality or non-infringement. WhiteList is not responsible for any SNS Content.
                    <br /><br />
                    11.4 When filling out the property registration form, you must provide information on the Accommodation including but not limited to location of a valid physical address, availability, capacity, size and features, as well as pricing, financial terms, and related rules. You agree that once a Tenant requests a booking of your Accommodation, you may not request the Tenant to pay a price higher than the price in the booking request.
                    <br /><br />
                    11.4.3 When a booking is requested for your Accommodation via the Website or Services, you as a Property must either confirm or decline the booking request within the Booking Request Period, otherwise the booking request will be automatically cancelled. When there is a booking request, WhiteList will show you the name of the Tenant requesting the booking and details associated with the booking request. If you do not confirm a booking request within the Booking Request Period, any amounts collected by WhiteList for the requested booking will be refunded to the Tenant and/or any pre-authorization related to the booking request will be cancelled. When you confirm a booking requested by the Tenant, WhiteList will send you an email, text message or message via the Website or Services, depending on the selections you specify via the Website or Services to confirm such booking.
                    <br /><br />
                    11.5 Tenant Fees for Accommodation
                    <br /><br />
                    11.5.1 The Total Fees payable will be shown to a Tenant before the Tenant sends a booking request to a Property. The Property is required to either confirm or decline the booking request within the Booking Request Period, or the requested booking will be automatically cancelled.
                    <br /><br />
                    11.6 Cancellation of a Booking Request and Cancellation of a Confirmed Booking
                    <br /><br />
                    11.6.1 If a Property cancels a confirmed booking made via the Website and Services,
                    <br /><br />
                    The Tenant will receive an email or other communication from WhiteList containing alternative Listings and other related information. If a Property cancelled a confirmed booking and you, as a Tenant, have not received an email or other communication from WhiteList, please contact WhiteList.
                    <br /><br />
                    11.6.2 If you as a Property cancel a confirmed booking, you agree that WhiteList may apply penalties or consequences to you or your Listing, including:
                    <br /><br />
                    Publishing an automated review on your listing indicating a reservation was cancelled;
                    <br /><br />
                    Keeping the calendar for your Listing unavailable or blocked for the dates of the cancelled booking; or
                    <br /><br />
                    Imposing a cancellation fee to be withheld from your future payouts or charged to the credit card on file in your WhiteList Account.
                    <br /><br />
                    You will be notified of the situations in which a cancellation fee applies before you agree to cancel.
                    <br /><br />
                    11.6.3 In certain circumstances, WhiteList may decide in its sole discretion that it is necessary or desirable to cancel a confirmed booking made via the Website and Services.
                    <br /><br />
                    11.6.4 As a Property, if your Tenant cancels a reservation or WhiteList decides it is necessary to cancel a confirmed booking, the property or WhiteList should process a reservation refund to the Tenant in accordance with the Tenant Refund Policy or other applicable refund policies.
                    <br /><br />
                    11.7 Laws that may apply to your properties
                    <br /><br />
                    Before you list your property at WhiteList, you need to consider the laws, ordinances, and regulations that are being implemented in your locale such as:
                    <br /><br />
                    Business Licenses, with information about it available in your city websites, or the city offices and customer service to explain the licensing process for your plan to list your property for short or long term rental;
                    <br /><br />
                    Zoning Code, Rules, and Ordinances dependent on rules cities have set on the use of your property, with information about it available in the city website;
                    <br /><br />
                    Any special permit required for renting your property, which you can check with the city website.</p>
                    <br /><br />        
                    <h2 className="terms-service-h2">12. Information regarding Tenant Overstaying without Property's consent and Damages to Accommodations</h2>
                    <p className="terms-service-p2">12.1 You as a Tenant agree that a confirmed reservation is merely a license granted by the Property to the Tenant to enter and use the Accommodation only for the limited duration of the confirmed reservation and in accordance with your agreement with the Property. You as a Tenant further agree to leave the Accommodation no later than the checkout time that the Property specifies in the Listing or such other time as mutually agreed upon between you and the Property. If you as a Tenant stays past the agreed upon checkout time without the Property's consent, you no longer have a license to stay in the Accommodation and the Property is entitled to demand your departure. In addition, you as a Tenant agree that the Property can charge you an additional nightly fee of two times the average nightly Accommodation Fee originally paid by you for each 24 hour period that you stay over the agreed period without the Property's consent in order to compensate for the inconvenience suffered by the Property, plus all applicable Services Fees, Taxes, and any legal expenses incurred by the Property to demand your departure (collectively, "Additional Sums").
                    <br /><br />  
                    12.2 You as a Tenant agree that you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals whom you invite to, or otherwise provide access to, the Accommodation. You as a Tenant are responsible for leaving the Accommodation in the condition it was in when you arrived. In the event that a Property claims damages and provides evidence of such damages, which may include but not be limited to photographic evidence, you agree to pay the cost of replacing the damaged items with equivalent items. After being notified of the claim and given forty eight (48) hours to respond, the payment will be collected from your security deposit.
                    <br /><br />  
                    12.3 You as a Property or a Tenant agree to cooperate with and assist WhiteList in good faith and to provide WhiteList with such information and take such actions as may be reasonably requested by WhiteList in connection with any complaints or claims made by Members relating to Accommodations or any personal or other property located at an Accommodation or with respect to any investigation undertaken by WhiteList or a representative of WhiteList regarding the use or abuse of the Website or the Services. Upon WhiteList's request, you as a Tenant agree to participate in mediation or similar resolution process with a Property.
                    </p>

                    <h2 className="terms-service-h2">13. Modifications to Services</h2>
                    <p className="terms-service-p2">13.1 WhiteList reserves the right at any time to modify or discontinue, temporarily or permanently, the Website or the Services, or any part thereof, with or without notice. You agree that WhiteList shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services. To protect the integrity of the Website or the Services, WhiteList reserves the right at any time in its sole discretion to block users from certain IP addresses from accessing the Website or Services.</p>

                    <h2 className="terms-service-h2">14. Copyright Policy; Notice and Procedure for Making Claims of Copyright Infringement</h2>
                    <p className="terms-service-p2">14.1 You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information:
                    <br /><br /> 
                    14.1.1 an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;
                    <br /><br /> 
                    14.1.2 a description of the copyrighted work that you claim has been infringed;
                    <br /><br /> 
                    14.1.3 a description of where the material that you claim is infringing is located on the Website, and such description must be reasonably sufficient to enable WhiteList to find the alleged infringing material, such as the url containing the claimed material infringed;
                    <br /><br /> 
                    14.1.4 your address, telephone number and email address;</p>

                    <h2 className="terms-service-h2">15. Communications and Test Profiles.</h2>
                    <p className="terms-service-p2">15.1 When you become a Member, you agree and consent to receive email messages from us. These emails may be transactional or relationship communications relating to the Services, such as administrative notices, Services announcements for changes, or emails containing commercial offers, promotions or special offers from us or third party partners. Please see WhiteList's Privacy Policy for more information regarding these communications. From time to time, employees of WhiteList or its parent or affiliated companies may create test dating profiles for the purpose of testing the functionality of our Services and website processes to improve Services quality for our Members. Telephone calls between you and our customer care representatives may be recorded for quality assurance purposes.</p>

                    <h2 className="terms-service-h2">16. Disclaimers</h2>
                    <p className="terms-service-p2">16.1 You acknowledge and agree that neither WhiteList nor its affiliates and third party partners are responsible for and shall not have any liability, directly or indirectly, for any loss or damage, including personal injury or death, as a result of or alleged to be the result of (i) any incorrect or inaccurate Content posted on the Website or provided in connection with the Services, whether caused by Members or any of the equipment or programming associated with or utilized in the Website or Services; (ii) the timeliness, deletion or removal, incorrect delivery or failure to store any Content, communications or personalization settings; (iii) the conduct, whether online or offline, of any Member; (iv) any error, omission or defect in, interruption, deletion, alteration, delay in operation or transmission, theft or destruction of, or unauthorized access to, any user or Member communications; or (v) any problems, failure or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to Members or to any other person's computer related to or resulting from participating or downloading materials in connection with the Internet and/or in connection with the Services. TO THE MAXIMUM EXTENT ALLOWED BY APPLICABLE LAW, WhiteList PROVIDES THE WEBSITE AND THE SERVICES ON AN "AS IS" AND "AS AVAILABLE" BASIS AND GRANTS NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE WITH RESPECT TO THE SERVICES OR THE WEBSITE INCLUDING ALL CONTENT CONTAINED THEREIN, INCLUDING (WITHOUT LIMITATION) ANY IMPLIED WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. WhiteList DOES NOT REPRESENT OR WARRANT THAT THE WEBSITE OR SERVICES WILL BE UNINTERRUPTED OR ERROR FREE, SECURE OR THAT ANY DEFECTS OR ERRORS ON THE WEBSITE OR IN THE SERVICES WILL BE CORRECTED.
                    <br /><br /> 
                    16.2 ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES OR WEBSITE IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER SYSTEM, INTERNET ACCESS, DOWNLOAD OR DISPLAY DEVICE, OR LOSS OR CORRUPTION OF DATA THAT RESULTS OR MAY RESULT FROM THE DOWNLOAD OF ANY SUCH MATERIAL. IF YOU DO NOT ACCEPT THIS LIMITATION OF LIABILITY, YOU ARE NOT AUTHORIZED TO DOWNLOAD OR OBTAIN ANY MATERIAL THROUGH THE SERVICES OR WEBSITE.
                    <br /><br /> 
                    16.3 From time to time, WhiteList may make third party opinions, advice, statements, offers, or other third party information or content available on the Website and/or through the Services. All third party content is the responsibility of the respective authors thereof and should not necessarily be relied upon. Such third party authors are solely responsible for such content. WhiteList DOES NOT: (I) GUARANTEE THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY THIRD PARTY CONTENT ON THE WEBSITE OR PROVIDED THROUGH THE SERVICES, OR (II) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE BY ANY PARTY THAT APPEARS ON THE WEBSITE OR SERVICES. UNDER NO CIRCUMSTANCES WILL WhiteList OR ITS AFFILIATES BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE RESULTING FROM YOUR RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE WEBSITE OR SERVICES, OR TRANSMITTED TO OR BY ANY MEMBERS.
                    <br /><br /> 
                    16.4 In addition to the preceding paragraph and other provisions of this Agreement, any advice that may be posted on the Website or through the Services is for informational and entertainment purposes only and is not intended to replace or substitute for any professional financial, medical, legal, or other advice. WhiteList makes no representations or warranties, and expressly disclaims any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Website or Services. If you have specific concerns or a situation arises in which you require professional or medical advice, you should consult with an appropriately trained and qualified specialist.</p>

                    <h2 className="terms-service-h2">17. Links</h2>
                    <p className="terms-service-p2">17.1 The Website may contain, and the Services or third parties may provide, advertisements and promotions offered by third parties and links to other websites or resources. You acknowledge and agree that WhiteList is not responsible for the availability of such external websites or resources, and does not endorse and is not responsible or liable for any content, information, statements, advertising, goods or Services, or other materials on or available from such websites or resources. Your correspondence or business dealings with, or participation in promotions of, third parties found on or through the Website or Services, including payment and delivery of related goods or Services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third party. You further acknowledge and agree that WhiteList shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of, or reliance upon, any such content, information, statements, advertising, goods or Services or other materials available on or through any such website or resource.
                    <br /><br /> 
                    Google Maps. Some of the Services implement the Google Maps web-mapping Services. Your use of Google Maps is subject to Google's terms of use, located at: http://www.google.com/intl/en_us/help/terms_maps.html</p>

                    <h2 className="terms-service-h2">18. Limitation on Liability</h2>
                    <p className="terms-service-p2">18.1 TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, IN NO EVENT WILL WhiteList, ITS AFFILIATES, BUSINESS PARTNERS, LICENSORS OR SERVICES PROVIDERS BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, RELIANCE, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OR CORRUPTION OF DATA OR PROGRAMS, SERVICES INTERRUPTIONS AND PROCUREMENT OF SUBSTITUTE SERVICES, EVEN IF WhiteList HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, WhiteList's LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO A CREDIT COUPON OF VALUE UP TO TEN PERCENT (10%) DISCOUNT ON FEES PAYABLE BY YOU TO WhiteList FOR SERVICES, WITH THE CREDIT COUPON EXPIRING IN THIRTY (30) DAYS. YOU AGREE THAT REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF OR RELATED TO YOUR USE OF THE WEBSITE OR SERVICES OR THE TERMS OF THIS AGREEMENT MUST BE FILED WITHIN ONE YEAR AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE OR BE FOREVER BARRED.</p>

                    <h2 className="terms-service-h2">19. Legal Disputes</h2>
                    <p className="terms-service-p2">19.1 Subject to the Company's right to seek injunctive relief in the courts of the Republic of the Philippines, any dispute, controversy or claim arising out of or in relation to or connection to the Terms and Conditions herein set forth, including without limitation any dispute as to the construction, validity, interpretation, enforceability or breach of any of the stipulations provided, shall be settled by arbitration in accordance with the Philippine Dispute Resolution Center, Inc. (PDRCI) Arbitration Rules as at present, in force.
                    <br /><br /> 
                    You agree to indemnify, defend, and hold WhiteList, its subsidiaries and affiliates, and their respective officers, directors, owners, agents, and information providers free and harmless from and against any and all claims, liabilities, losses, costs and expenses incurred in connection with any breach by you of these Terms and Conditions.</p>

                    <h2 className="terms-service-h2">20. Indemnity by You</h2>
                    <p className="terms-service-p2">20.1 You agree to release, indemnify and hold WhiteList, its subsidiaries, and affiliates, and its and their officers, agents, partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your breach of or failure to comply with this Agreement, including any breach of your representations and warranties contained herein, and in any matter, any postings or Content you post on the Website or as a result of the Services, and the violation of any law or regulation by you. This includes but not limited to any injuries, losses, or damages, that is compensatory, direct, incidental, consequential or otherwise, of any kind incorrectly arising in connection with or as a result of a rental, booking or use of an Accommodation; and (e) your participation in the Referral Program or your accrual of any WhiteList Discounts. WhiteList reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with WhiteList in connection therewith.</p>
                    
                    <h2 className="terms-service-h2">21. Notice</h2>
                    <p className="terms-service-p2">21.1 WhiteList may provide you with notices, including those regarding changes to this Agreement, using any reasonable means now known or hereafter developed, including by email, regular mail, SMS, text message or postings on the Website. Such notices may not be received if you violate this Agreement by accessing the Services in an unauthorized manner. You agree that you are deemed to have received any and all notices that would have been delivered had you accessed the Services in an authorized manner.</p>

                    <h2 className="terms-service-h2">22. Entire Agreement; Other</h2>
                    <p className="terms-service-p2">22.1 This Agreement, with the Privacy Policy and any specific guidelines or rules that are separately posted for particular Services or offers on the Website, contains the entire agreement between you and WhiteList regarding your use of the Website and/or the Services. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect. The failure of WhiteList to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision. You agree that your online account is non-transferable and all of your rights to your profile or contents within your account terminate upon your death. No agency, partnership, joint venture or employment is created as a result of this Agreement and you may not make any representations or bind WhiteList in any manner.</p>

                    <h2 className="terms-service-h2">23. Amendment</h2>
                    <p className="terms-service-p2">23.1 This Agreement is subject to change by WhiteList at any time. The revised terms will be effective upon posting on the Website, and your use of the Services after such posting will constitute acceptance by you of the revised Agreement.</p>
                    
                    <h2 className="terms-service-h2">24. Contact Information</h2>
                    <p className="terms-service-p2">Questions or concerns: hello@whitelist.ph</p>

                    </div>
            </motion.body>
        </>
    )
}

export default TermsService