import Img20 from '../../images/house1.jpg';
import Img21 from '../../images/house2.jpg';
import Img22 from '../../images/house3.jpg';
import Img23 from '../../images/house4.jpg';
import Img24 from '../../images/house5.jpg';
import Img25 from '../../images/house6.jpg';
import Img26 from '../../images/house7.jpg';
import Img27 from '../../images/house8.jpg';
import Img28 from '../../images/house9.jpg';
import Img29 from '../../images/house10.jpg';
import Img30 from '../../images/house11.jpg';
import Img31 from '../../images/house12.jpg';
import Img32 from '../../images/house13.jpg';
import Img33 from '../../images/house14.jpg';
import Img34 from '../../images/house15.jpg';

const sampleData = [
    {
        name:'Abaka',
        description: 'Abaka is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img20,
        category:'lodginghouse',
        value: 'Lahug, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 5, 
        key: 1,
        id: '#1'
    },
    {
        name:'Edaha',
        description: 'Edaha is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Boarding House',
        units: 'month',
        minPrice: 2500.00,
        maxPrice: 3000.00,
        capacity: '2 boarders',
        available: 10,
        total: 10,
        imgs: Img21,
        category:'boardinghouse',
        value: 'Mambaling, Cebu City',
        amenities: ["TV set","Wi-fi","Single Bed"],
        stars: 5, 
        key: 2,
        id: '#2'
    },
    {
        name:'Ilama',
        description: 'Ilama is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Apartment',
        units: 'month',
        minPrice: 3500.00,
        maxPrice: 4000.00,
        capacity: '4 to 5 heads',
        available: 3,
        total: 5,
        imgs: Img22,
        category:'apartment',
        value: 'Tisa, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 2, 
        key: 3,
        id: '#3'
    },
    {
        name:'Naupa',
        description: 'Naupa is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Apartment',
        units: 'month',
        minPrice: 3500.00,
        maxPrice: 4000.00,
        capacity: '4 to 5 heads',
        available: 3,
        total: 5,
        imgs: Img23,
        category:'apartment',
        value: 'Ramos, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 5, 
        key: 4,
        id: '#4'
    },
    {
        name:'Rasata',
        description: 'Rasata is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Rent House',
        units: 'month',
        minPrice: 7000.00,
        maxPrice: 7000.00,
        capacity: 'unlimited',
        available: 1,
        total: 1,
        imgs: Img24,
        category:'renthouse',
        value: 'Talisay City',
        amenities: ["TV set","Wi-fi"],
        stars: 3, 
        key: 5,
        id: '#5'
    },
    {
        name:'Juan',
        description: 'Juan is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img25,
        category:'lodginghouse',
        value: 'Bulacao, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 5,
        key: 6,
        id: '#6'
    },
    {
        name:'Maria',
        description: 'Maria is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lease',
        units: 'month',
        minPrice: 12000.00,
        maxPrice: 12000.00,
        capacity: '6 years',
        available: 1,
        total: 1,
        imgs: Img26,
        category:'lease',
        value: 'Lahug, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 4, 
        key: 7,
        id: '#7'
    },
    {
        name:'Carlos',
        description: 'Carlos is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Hotel',
        units: 'night',
        minPrice: 3500.00,
        maxPrice: 6000.00,
        capacity: '1 to 4 heads',
        available: 0,
        total: 0,
        imgs: Img27,
        category:'hotel',
        value: 'Bulacao, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 2, 
        key: 8,
        id: '#8'
    },
    {
        name:'Sibila',
        description: 'Sibila is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img28,
        category:'lodginghouse',
        value: 'Talisay City',
        amenities: ["TV set","Wi-fi"],
        stars: 1, 
        key: 9,
        id: '#9'
    }, 
    {
        name:'Jose',
        description: 'Jose is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Apartment',
        units: 'month',
        minPrice: 3500.00,
        maxPrice: 4000.00,
        capacity: '4 to 5 heads',
        available: 3,
        total: 5,
        imgs: Img29,
        category:'apartment',
        value: 'Talisay City',
        amenities: ["TV set","Wi-fi","Laundromat"],
        stars: 4, 
        key: 10,
        id: '#10'
    }, 
    {
        name:'Felipe',
        description: 'Felipe is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img30,
        category:'lodginghouse',
        value: 'Mambaling, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 3, 
        key: 11,
        id: '#11'
    }, 
    {
        name:'Cardo',
        description: 'Cardo is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img31,
        category:'lodginghouse',
        value: 'Mambaling, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 2, 
        key: 12,
        id: '#12'
    },
    {
        name:'Dalisay',
        description: 'Dalisay is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Hotel',
        units: 'night',
        minPrice: 3500.00,
        maxPrice: 6000.00,
        capacity: '1 to 4 heads',
        available: 0,
        total: 0,
        imgs: Img32,
        category:'hotel',
        value: 'Bulacao, Cebu City',
        amenities: ["TV set","Wi-fi","Bathtub"],
        stars: 4, 
        key: 13,
        id: '#13'
    },
    {
        name:'Elena',
        description: 'Elena is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Lodging House',
        units: 'hour',
        minPrice: 150.00,
        maxPrice: 500.00,
        capacity: '2 to 3 heads',
        available: 8,
        total: 10,
        imgs: Img33,
        category:'lodginghouse',
        value: 'Talisay City',
        amenities: ["TV set","Wi-fi"],
        stars: 5, 
        key: 14,
        id: '#14'
    },
    {
        name:'Sebastian',
        description: 'Sebastian is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike. Lorem Ipsum is a charming six-floored coliving space of semi-furnished rooms for rent in Guadalupe Nuevo, Makati, near Kalayaan Ave., EDSA, Guadalupe, and BGC. Complete with basic amenities needed, its communal areas are suitable study and socialization spots for students and roomies alike.', 
        categoryName:'Boarding House',
        units: 'month',
        minPrice: 2500.00,
        maxPrice: 3000.00,
        capacity: '2 boarders',
        available: 10,
        total: 10,
        imgs: Img34,
        category:'boardinghouse',
        value: 'Bulacao, Cebu City',
        amenities: ["TV set","Wi-fi"],
        stars: 3, 
        key: 15,
        id: '#15'
    }
];

export default sampleData;